/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: ['./src/**/*.{ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        background: '#08111F',
        surface: '#0E1A2B',
        'surface-elevated': '#142238',
        'surface-muted': '#192A42',
        border: '#263A55',
        primary: '#2DD4BF',
        'primary-pressed': '#14B8A6',
        'primary-soft': '#123D3B',
        content: {
          primary: '#F4F7FB',
          secondary: '#AAB8CC',
          muted: '#71819A',
        },
        success: '#4ADE80',
        warning: '#FBBF24',
        error: '#FB7185',
        info: '#60A5FA',
        vip: '#C084FC',
        scrim: 'rgba(0,0,0,0.64)',
        light: {
          background: '#F5F7FA',
          surface: '#FFFFFF',
          'surface-elevated': '#FFFFFF',
          'surface-muted': '#EAF0F5',
          border: '#D5DEE9',
          primary: '#0F766E',
          'primary-pressed': '#115E59',
          'primary-soft': '#CCFBF1',
          content: {
            primary: '#102033',
            secondary: '#475569',
            muted: '#718096',
          },
          success: '#15803D',
          warning: '#B45309',
          error: '#BE123C',
          info: '#1D4ED8',
          vip: '#7E22CE',
          scrim: 'rgba(0,0,0,0.48)',
        },

        // Compatibility aliases for current screens/components.
        foreground: '#F4F7FB',
        muted: '#AAB8CC',
        primarySoft: '#123D3B',
        surfaceElevated: '#142238',
        surfaceMuted: '#192A42',
        danger: '#FB7185',
        seeders: '#4ADE80',
        leechers: '#FBBF24',
      },
      borderRadius: {
        sm: '8px',
        md: '12px',
        lg: '16px',
        xl: '24px',
        full: '999px',
      },
    },
  },
  plugins: [],
};
